stages:
  - build
  - valgrind

build-job:
  stage: build
  tags:
    - shared
  image: gcc:latest
  script:
    - make slist
  artifacts:
    paths:
      - ./slist
    expire_in: "7 days"

memcheck-job:
  stage: valgrind
  tags:
    - shared
  image: gcc:latest
  script:
    - apt update
    - apt-get install -y valgrind
    - valgrind --leak-check=yes ./slist < test | tee > memcheckresult.txt
  artifacts:
    paths:
      - ./memcheckresult.txt
    expire_in: "7 days"
