stages:
  - build
  - test
  - valgrind

build-job:
  stage: build
  tags:
    - shared
  image: gcc:latest
  script:
    - make slist
  artifacts:
    paths:
      - ./slist
    expire_in: "7 days"
test-job:
  stage: build
  tags:
    - shared
  image: gcc:latest
  script:
    - make tests
  artifacts:
    paths:
      - ./tests
    expire_in: "7 days"
memcheck-job:
  stage: valgrind
  tags:
    - shared
  image: gcc:latest
  script:
    - apt update
    - apt-get install -y valgrind
    - valgrind --leak-check=yes ./slist < ./tests/test1 | tee >> memcheckresult.txt
    - valgrind --leak-check=yes ./slist < ./tests/test2 | tee >> memcheckresult.txt
    - valgrind --leak-check=yes ./slist < ./tests/test3 | tee >> memcheckresult.txt
  artifacts:
    paths:
      - ./memcheckresult.txt
    expire_in: "7 days"
